version: '2'
services:
    overnightcarrepairs-mongodb:
        image: mongo:4.0.4
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/overnightcarRepairs/mongodb/:/data/db/
