- name: load push ConfigMap
  k8s:
    name: push-configmap
    kind: ConfigMap
    api_version: v1
    state: present
    namespace: 'push' # Use kub_variables in playbook
    definition:
      data:
        difinitions.json: "{{ lookup('file', 'templates/config.json') | string }}"