- name: load Service
  k8s:
    name: push-service
    kind: Service
    api_version: v1
    state: present
    namespace: 'push' # Use kub_variables in playbook
    definition:
      spec:
        ports:
        - name: push-port
          port: 8080 # External Port
          protocol: TCP
          targetPort: 8080 # Port in container
        selector:
          app: push # POD Name
        sessionAffinity: None
        type: ClusterIP
      status:
        loadBalancer: {}